version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 99
  target-branch: dev
  ignore:
  - dependency-name: "@docusaurus/core"
    versions:
    - "> 2.0.0-alpha.58"
  - dependency-name: "@docusaurus/preset-classic"
    versions:
    - "> 2.0.0-alpha.58"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.2.0
